function drop_num = get_drop_num(dirname)
% GET_DROP_NUM Extracts the HAARS drop number from a directory name
%   This function was generated by ChatGPT and reviewed by a human
%
%   This function is used primarily for identifying drops for analysis and
%   cross-referencing truth data. Note that it only works and is only
%   useful for directory names with the specific HAARS format
%
% INPUTS:
%   dirname  : The directory name
%
% OUTPUTS:
%   drop_num : The drop number

% Use REGEX 
tokens = regexp(dirname, 'DN(\d+)', 'tokens');

% Check the drop number does exist
if ~isempty(tokens)
    drop_num = str2double(tokens{1}{1});
else
    drop_num = NaN;
end

end