% EXTRACTWINDSINRANGE Sample a wind profile at regular altitude intervals.
%   Interpolates the wind profile at evenly spaced altitude steps within
%   the specified range, producing a dense set of wind samples for use in
%   vectorial averaging.
%
% INPUTS:
%   windProfile : Nx3 array of [altitude(ft), direction(°), speed(kts)]
%                 wind profile data, sorted by altitude ascending
%   minAlt      : Lower bound of the altitude range to sample (ft)
%   maxAlt      : Upper bound of the altitude range to sample (ft)
%   interval    : Altitude step size between samples (ft)
%
% OUTPUTS:
%   windsOut : Mx2 array of [direction(°), speed(kts)] wind samples,
%              where M = length(minAlt:interval:maxAlt)
%
% NOTES:
%   - If minAlt == maxAlt, a single sample is returned at that altitude.
%   - Altitudes outside the windProfile range are clamped to the nearest
%     profile endpoint by interpolateWind.
%   - The number of output rows equals the number of sample points
%     generated by minAlt:interval:maxAlt (inclusive on both ends).
%
% See also INTERPOLATEWIND, VECTORIALAVERAGEWIND, COMPUTEBALLISTICWINDS

function windsOut = extractWindsInRange(windProfile, minAlt, maxAlt, interval)
            % Extract winds at specified intervals within altitude range
            altitudes = minAlt:interval:maxAlt;
            windsOut = zeros(length(altitudes), 2);
            
            for i = 1:length(altitudes)
                windsOut(i, :) = interpolateWind(windProfile, altitudes(i));
            end
        end